### ISSUE TITLE
[Twilight Forest] Crash after using magic map

### ISSUE THREAD

**Issue by fireboy637** [BluSpring/Kilt#266]
### Version information

0.0.1-mc1.20.1-build.36eacd9

### Reproduction Steps

After installing Twilight Forest, in twilight forest dimension, use blank magic map, and then crash.

### Java Provider + Version

Azul zulu 17.0.12

### Crash Report file

[crash-2025-05-05_13.48.02-server.txt](https://github.com/user-attachments/files/20032054/crash-2025-05-05_13.48.02-server.txt)

[latest.log](https://github.com/user-attachments/files/20032055/latest.log)

### Additional information

Only the latest Kilt dependent mods and Indium are installed.

**Comment by BluSpring** [comment]
Could you try this again? I implemented this a while ago and it should be somewhat functional now

**Comment by fireboy637** [comment]
No, it doesn't work.
I tried commit 9a8402, but Minecraft still crashed. Here's the [crash report](https://mclo.gs/brrf77u) and [latest.log](https://mclo.gs/4zL0ttg).


Also, I found more problems.
As I walked through the Twilight Forest Portal, the world update seemed like a mess. It seems that the server can't handle block updates correctly, and the something like "ghost block" appears, but I can't fix that by using mod [AntiGhost](https://modrinth.com/mod/antighost). At this time, if I switch dimensions, the anomaly will disappear.
What's more, I use seed -849418999086906189, and when I pass through the Twilight Forest Portal at (X:1,Z:4), my player has a high chance of spawning in a Lich Tower. It shouldn't happen.
Also, Twilight Forest can't be loaded on server.

I'm not sure if I should file these issues in separate issues at this point. I probably won't be playing Kilt until it's updated to a newer version of Minecraft, but these issues may help improve compatibility.

**Comment by BluSpring** [comment]
Server-side at least is known, but I'll take a look at everything else when I can

**Comment by Cartrigger** [comment]
the magic map seems to be fine, but i spawned in a naga when i went through the portal, and the ghost blocks still exist
